name: nginx-docker-image-build

on:
  push:
  schedule:
    - cron: '0 */8 * * *'

jobs: 
  nginx-docker-image-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: docker login
        run: docker login -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERAPIKEY }}
      - name: treehouses nginx
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
